language: php
services: 
   - mysql
matrix:
 include:
   - php: 7.2
     dist: bionic
   - php: 7.3
     dist: bionic
 fast_finish: true
 
before_install:
  - sudo apt-get update > /dev/null
  
install:
  - sudo apt-get install php apache2

before_script:
  - mysql -e "create database cacti;"
  - mysql -e "CREATE USER 'cactiuser'@'localhost' IDENTIFIED BY 'cactiuser';"
  - mysql -e "GRANT ALL PRIVILEGES ON cacti.* TO 'cactiuser'@'localhost';"
  - mysql -e "flush privileges;"

script: true

notifications: 
 email: 
   on_success: change
   on_failure: always
   

 
  
  
     
     
